name: cicd
on:
  push:
  create:
  workflow_dispatch:

jobs:
  branch:
    name: branch
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
    - run: |
        echo ${GITHUB_REF}

  app1:
    name: app1
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
    - uses: actions/checkout@v2
    - run: cat ./app1/app1.txt

  app2:
    name: app2
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
    - uses: actions/checkout@v2
    - run: cat ./app2/app2.txt
