name: cicd
on:
  push:
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      app1: ${{ steps.filter.outputs.app1 }}
      app2: ${{ steps.filter.outputs.app2 }}
    steps:
    # For pull requests it's not necessary to checkout the code
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        base: ${{ github.ref }}
        filters: |
          app1:
            - 'app1/**'
          app2:
            - 'app2/**'

  app1:
    name: app1
    needs: [changes]
    if: needs.changes.outputs.app1 == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
    - uses: actions/checkout@v2
    - run: cat ./app1/app1.txt

  app2:
    name: app2
    needs: [changes]
    if: needs.changes.outputs.app2 == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
    - uses: actions/checkout@v2
    - run: cat ./app2/app2.txt
